MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RPN:
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    PRE_NMS_TOP_N_TRAIN: 12000
  ROI_BOX_HEAD:
    NUM_CLASSES: 9
    POOLER_RESOLUTION: 7
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
  PMM_TH: 0.99
  CLS_LOSS_FUNC: 'ce'
  NOISETRANSFER_DA_ON: True
  NOISEGRADMATCH_ON: True
  EAGR_LR: 10
  MY_HEAD_UPDATE: 'cos'
  FISH_PERIOD: 2
DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  ANNOTATIONS: None
  SOURCE_TRAIN: ('cityscapes_train_cocostyle',)
  TARGET_TRAIN: ('cityscapes_foggy_train_cocostyle',)
  TEST: ('cityscapes_foggy_val_cocostyle',)
  TRAIN: ('cityscapes_train_cocostyle',)
INPUT:
  MIN_SIZE_TRAIN: (800,) # 600
  MAX_SIZE_TRAIN: 1600 # 1333
  MIN_SIZE_TEST: 800 # 600
  MAX_SIZE_TEST: 1600 # 1333
SOLVER:
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 2500
  IMS_PER_BATCH: 2
  MAX_ITER: 70000
  STEPS: (50000,)
  TEST_ONLY: False
  VAL_ITER: 2500
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR:
  "./work_dir/da_c2f"
