MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  DOMAIN_ADAPTATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 512
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
  CLS_LOSS_FUNC: 'ce'
  NOISETRANSFER_DA_ON: True
  NOISEGRADMATCH_ON: True
  EAGR_LR: 10
  MY_HEAD_UPDATE: 'cos'
  FISH_PERIOD: 2
DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  SOURCE_TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TARGET_TRAIN: ("clipart_traintest",)
  TEST: ("clipart_traintest",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1200
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000, 60000)
  MAX_ITER: 70000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR:
  "./work_dir/da_p2c"
